environment:
    prod:
      source:
          base_url: "https://b2c.passport.rt.ru/account_b2c/page?state=924dba8c-fd63-4430-bdad-2cfc910629f8&client_id=account_b2c#/"
          auth_url: "https://b2c.passport.rt.ru/auth/realms/b2c/protocol/openid-connect/auth?client_id=account_b2c&redirect_uri=https://b2c.passport.rt.ru/account_b2c/login&response_type=code&scope=openid&state=924dba8c-fd63-4430-bdad-2cfc910629f8&theme&auth_type"
          reg_url: "https://b2c.passport.rt.ru/auth/realms/b2c/login-actions/registration?client_id=account_b2c&tab_id=R-laTmothbs"
